// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    public partial class TbItems
    {
        public TbItems()
        {
            TbItemUnits = new HashSet<TbItemUnits>();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string ActiveIngredient { get; set; }
        public string Company { get; set; }
        public string Pamphlet { get; set; }
        public string Dosage { get; set; }
        public string Composition { get; set; }
        public int CategoryId { get; set; }
        [Required]
        public bool? IsActive { get; set; }
        public string ImageName { get; set; }
        public bool? IsDeleted { get; set; }
        public string Brief { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("TbItems")]
        public virtual TbCategories Category { get; set; }
        [InverseProperty("Item")]
        public virtual ICollection<TbItemUnits> TbItemUnits { get; set; }
    }
}