// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    public partial class TbItemUnits
    {
        public TbItemUnits()
        {
            TbOrdersItems = new HashSet<TbOrdersItems>();
            TbSalesInvoiceItems = new HashSet<TbSalesInvoiceItems>();
        }

        [Key]
        public int Id { get; set; }
        public int? ItemId { get; set; }
        public int? UnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalesPrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? PuchasePrice { get; set; }
        [StringLength(200)]
        public string Barcode { get; set; }
        public int? UnitsNumber { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey("ItemId")]
        [InverseProperty("TbItemUnits")]
        public virtual TbItems Item { get; set; }
        [ForeignKey("UnitId")]
        [InverseProperty("TbItemUnits")]
        public virtual TbUnits Unit { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbOrdersItems> TbOrdersItems { get; set; }
        [InverseProperty("ItemUnit")]
        public virtual ICollection<TbSalesInvoiceItems> TbSalesInvoiceItems { get; set; }
    }
}