// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    public partial class TbOrders
    {
        public TbOrders()
        {
            TbOrdersItems = new HashSet<TbOrdersItems>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        public int? CustomerId { get; set; }
        [StringLength(450)]
        public string PatientId { get; set; }
        [StringLength(50)]
        public string BloodPressure { get; set; }
        public int Diabites { get; set; }
        public int BodyTempreature { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NextVisit { get; set; }
        public string Diagnosis { get; set; }
        public string Notes { get; set; }
        [StringLength(50)]
        public string OrderType { get; set; }

        [ForeignKey("CustomerId")]
        [InverseProperty("TbOrders")]
        public virtual TbCustomers Customer { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<TbOrdersItems> TbOrdersItems { get; set; }
    }
}