// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    public partial class TbOrdersItems
    {
        [Key]
        public int Id { get; set; }
        public int? ItemUnitId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        public int? OrderId { get; set; }
        public string Notes { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "decimal(37, 4)")]
        public decimal? Total { get; set; }

        [ForeignKey("ItemUnitId")]
        [InverseProperty("TbOrdersItems")]
        public virtual TbItemUnits ItemUnit { get; set; }
        [ForeignKey("OrderId")]
        [InverseProperty("TbOrdersItems")]
        public virtual TbOrders Order { get; set; }
    }
}