// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    public partial class TbUnits
    {
        public TbUnits()
        {
            TbItemUnits = new HashSet<TbItemUnits>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }

        [InverseProperty("Unit")]
        public virtual ICollection<TbItemUnits> TbItemUnits { get; set; }
    }
}