// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Pharmacy_DomainModels.Models.DB_Models
{
    [Keyless]
    public partial class VwOrderItem
    {
        public int? OrderId { get; set; }
        public string Name { get; set; }
        public string ImageName { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Qty { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Price { get; set; }
        [Column(TypeName = "decimal(37, 4)")]
        public decimal? Total { get; set; }
        public string Notes { get; set; }
        public int? ItemUnitId { get; set; }
    }
}